name: setalpha
description: A convenience package for setting and accessing web colors, adjusting the alpha levels of given colors and mixing new colors.
version: 1.0.0
homepage: https://bitbucket.org/ram6ler/setalpha/wiki/Home

environment:
  sdk: '>=2.7.0 <3.0.0'

