name: setalpha
description: A starting point for Dart libraries or applications.
version: 0.5.0
homepage: https://ram6ler@bitbucket.org/ram6ler/setalpha
author: Richard Ambler <rambler@ibwya.net.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
