name: setalpha
description: A convenience package for setting and accessing web colors, adjusting the alpha levels of given colors and mixing new colors.
version: 2.0.0
homepage: https://bitbucket.org/ram6ler/setalpha/wiki/Home

environment:
  sdk: '>=2.18.0 <3.0.0'

