name: setalpha
description: A convenience package for setting and accessing web colors, adjusting the alpha levels of given colors and mixing new colors.
version: 0.9.2
homepage: https://bitbucket.org/ram6ler/setalpha/wiki/Home
author: Richard Ambler <rambler@ibwya.net.com>

environment:
  sdk: '>=2.0.0-dev.69.3 <3.0.0'

