name: setalpha
description: A convenience package for setting and accessing web colors, adjusting the alpha levels of given colors and mixing new colors.
version: 0.9.0
homepage: https://ram6ler@bitbucket.org/ram6ler/setalpha
author: Richard Ambler <rambler@ibwya.net.com>

environment:
  sdk: '>=2.0.0-dev.69.4 <3.0.0'

